services: # Liste des serveurs
  database: # Nom du service de la DB
    container_name: gamer_challenge_db
    image: postgres:18 # Image permettant de créer le conteneur
    restart: unless-stopped # Redémarre automatiquement mon service en cas de crash (sauf s'il a été éteint manuellement)
    volumes:
      - gamer_challenge_volume:/var/lib/postgresql # On monte un volume pour la persistence de donnée
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_LOCAL_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: gamer_challenge_api
    build:
      context: .
      dockerfile: Dockerfile-api
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public"
    ports:
      - ${API_LOCAL_PORT}:3000
      - 51212:51212
    depends_on:
      database:
        condition: service_healthy

volumes: # Liste de nos volumes
  gamer_challenge_volume: # Volume pour la persistance des données de la DB
