# ===== STAGE 1 : "builder" =====
# Cette image va compiler, puis être JETÉE
FROM node:24-alpine AS builder
RUN apk add --no-cache openssl
RUN corepack enable
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile    # ← installe TOUT (dev + prod)

COPY . .
RUN pnpm run db:generate              # ← génère le client Prisma
RUN pnpm run build                    # ← compile TS → JS dans dist/

# À la fin de ce stage, on a : dist/, generated/, node_modules complet,
# code source, types, etc. Cette image va exister temporairement.

# ===== STAGE 2 : image finale =====
# C'est CELLE-CI qui sera publiée et exécutée
FROM node:24-alpine
RUN apk add --no-cache openssl
RUN corepack enable
WORKDIR /app

# Réinstallation, mais cette fois UNIQUEMENT les deps de prod
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod   # ← --prod = pas de devDeps

# On récupère du builder UNIQUEMENT les artefacts compilés
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/generated ./generated
COPY --from=builder /app/prisma ./prisma

USER node
CMD ["pnpm", "run", "docker:start"]
