FROM node:24-alpine

RUN apk add --no-cache openssl

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run db:generate

RUN pnpm run build

CMD ["pnpm", "run", "docker:start"]
